version: '3.9'

#O build . -> pra dar comando de construi a img atual, comand->comando q vai dar depois q toda a img for construida, volume -> dedicando qual vai ser o volume da nossa aplicação, depences_on -> é o db que é o banco de dados dai em baixo configura as infos do db que tem ser a mesmas que estao no env.dev pra da certo 
services: 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./env.dev
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    ports: 
      - 5433:5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=twitter_dev
      - POSTGRES_PASSWORD=twitter_dev
      - POSTGRES_DB=twitter_db
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  app_data:
