# Generated by Django 5.1.6 on 2025-07-11 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0002_perfil"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="seguidores",
            field=models.ManyToManyField(
                blank=True, related_name="seguindo", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
