# Generated by Django 5.1.6 on 2025-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0003_perfil_seguidores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="perfil/"),
        ),
    ]
